#!/usr/bin/env bash
#
# post-install
# Based on ubuntu-post-install by Sam Hewitt <sam@snwh.org>
# github.com/drieiro/post-install
#

# tab width
tabs 4
clear

# Script title
TITLE="post-install"

# Install script dependencies
function dependencies {
    for dep in $(cat $(dirname "$0")/dependencies); do
        if dpkg -l | grep "$dep" &>/dev/null; then
            echo_message success "Dependency '$dep' installed!"
        else
            echo_message info "Installing '$dep'..."
            sudo apt install "$dep" &>/dev/null
        fi
    done
}

# Import scriptset functions
function import_functions {
    for function in $(dirname "$0")/data/*; do
        [ ! -d $function ] && source $function
    done
}

function internet {
    if ping -c2 www.google.com &> /dev/null; then
        echo_message success "There is an internet connection established!"
    else
        echo_message error "There is not an internet connection established."
        exit 99
    fi
}

function main {
    MAIN=$(eval `resize` && whiptail \
        --notags \
        --title "$TITLE" \
        --menu "\nWhat would you like to install?" \
        --cancel-button "Quit" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'install_dotfiles'      'Install dotfiles' \
        'install_alacritty'     'Alacritty' \
        'install_anydesk'       'AnyDesk' \
        'install_bashblog'      'Bashblog' \
        'install_brave'         'Brave Browser' \
        'install_calibre'       'Calibre' \
        'install_chrome'        'Google Chrome' \
        'install_dconf'         'dconf editor' \
        'install_discord'       'Discord' \
        'install_dropbox'       'Dropbox' \
        'install_easytag'       'Easytag' \
        'install_etweaks'       'elementary tweaks' \
        'install_firefox'       'Firefox' \
        'install_gdocamlfuse'   'google-drive-ocamlfuse' \
        'install_gimp'          'GIMP' \
        'install_gnometweaks'   'gnome-tweaks' \
        'install_handbrake'     'HandBrake' \
        'install_hplip'         'HPLIP' \
        'install_imageburner'   'Imageburner' \
        'install_java8'         'Java8' \
        'install_keepassxc'     'KeePassXC' \
        'install_libreoffice'   'LibreOffice' \
        'install_linuxmintwebappmanager'           'Linux Mint Webapp Manager' \
        'install_megasync'      'MegaSync' \
        'install_mpv'           'mpv' \
        'install_neovim'        'Neovim' \
        'install_opera'         'Opera' \
        'install_pdftricks'     'PDF Tricks' \
        'install_picard'        'MusicBrainz Picard' \
        'install_planner'       'Planner' \
        'install_playmymusic'   'Melody' \
        'install_rclone'        'rclone' \
        'install_simplescreenrecorder'  'simplescreenrecorder' \
        'install_skype'         'Skype' \
        'install_spotify'       'Spotify' \
        'install_synaptic'      'Synaptic' \
        'install_teamviewer'    'TeamViewer' \
        'install_telegram'      'Telegram' \
        'install_terminal'      'Terminal stuff' \
        'install_themes'        'Themes and icons' \
        'install_thunderbird'   'Thunderbird' \
        'install_timeshift'     'Timeshift' \
        'install_transmission'  'Transmission' \
        'install_ulauncher'     'Ulauncher' \
        'install_unrar'         'RAR' \
        'install_virtualbox'    'VirtualBox' \
        'install_vlc'           'VLC' \
        'install_vscode'        'Visual Studio Code' \
        'install_vscodium'      'VSCodium' \
        'install_wireshark'     'Wireshark' \
        'install_youtube-dl'    'youtube-dl' \
        'install_yt-dlp'        'yt-dlp' \
        'install_zsh'           'zsh' \
        3>&1 1>&2 2>&3)
    if [ $? = 0 ]; then
        $MAIN
    else
        # Quit
        quit
    fi
}

function quit {
    # Draw window
    if (whiptail --title "Quit" --yesno "Are you sure you want quit?" 8 56); then
            echo 'Thanks for using!'
            exit 99
    else
            main
    fi
}

import_functions
welcome
internet
dependencies
check_os
check_distribution

while :
do
    main
done
