#!/usr/bin/env bash

function check_os {
	echo_message title "Checking which OS you are using..."
	# Variables
	OS_NAME="Linux"
	# Check if Linux
	echo_message info "Current OS is: "$(uname)
	if [[ $(uname) != "$OS_NAME" ]]; then
		echo_message error "You don't appear to be using $OS_NAME! Aborting. :("
		exit 99
	else
		echo_message success "You are using '$OS_NAME'. :D"
	fi
}

# Check which distribution the user is running
function check_distribution {
	# check if 'lsb_release' exists
	if [[ $(which lsb_release &>/dev/null; echo $?) != 0 ]]; then
		echo_message error "\aCan't check which distribution you are using! Aborting."
		echo_message error " Aborting..." && sleep 3 && exit 99
	else
		# if Ubuntu
		if lsb_release -ds | grep -qE '(Ubuntu|elementary)'; then
			echo_message info 'Current distribution is: '$(lsb_release -ds)
                        echo_message success "You are using $(lsb_release -si). :D"
			echo "Proceeding."
		# if Mint or elementary
		elif lsb_release -ds | grep -qE '(Mint|Zorin)'; then
			echo_message info 'Current distribution is: '$(lsb_release -ds)
			echo_message success "You are using an Ubuntu-based distribution. It's probably fine. :)"
			echo "Proceeding."
		# if Debian
		elif lsb_release -ds | grep -q 'Debian'; then
			echo 'Current distribution is: '$(lsb_release -ds)
			echo_message warning "You are using Debian. This is not recommended. Some functions may not work. :/"
			echo "Proceeding nonetheless."
		# if anything else
		else
			echo_message warning "You are using a distribution that may not be compatible with this script set."
			echo_message warning "Proceeding may break your system."
			echo_message question "Are you sure you want to continue? (Y)es, (N)o : " && read REPLY
			case $REPLY in
			# Positive action
			[Yy]* )
				echo_message warning "You have been warned."
				;;
			# Negative action
			[Nn]* )
				echo_message info "Exiting..."
				exit 99
				;;
			# Error
			* )
				echo_message error 'Sorry, try again.' && check_distribution
				;;
			esac
		fi
	fi
}

